USE [master]
GO

/****** Object:  Database [BatallaNaval]    Script Date: 22-Nov-22 22:37:01 ******/
CREATE DATABASE [BatallaNaval]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BatallaNaval', FILENAME = N'D:\SQL2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\BatallaNaval.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BatallaNaval_log', FILENAME = N'D:\SQL2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\BatallaNaval_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BatallaNaval].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BatallaNaval] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BatallaNaval] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BatallaNaval] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BatallaNaval] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BatallaNaval] SET ARITHABORT OFF 
GO

ALTER DATABASE [BatallaNaval] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BatallaNaval] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BatallaNaval] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BatallaNaval] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BatallaNaval] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BatallaNaval] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BatallaNaval] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BatallaNaval] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BatallaNaval] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BatallaNaval] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BatallaNaval] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BatallaNaval] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BatallaNaval] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BatallaNaval] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BatallaNaval] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BatallaNaval] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BatallaNaval] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BatallaNaval] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BatallaNaval] SET  MULTI_USER 
GO

ALTER DATABASE [BatallaNaval] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BatallaNaval] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BatallaNaval] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BatallaNaval] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BatallaNaval] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BatallaNaval] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BatallaNaval] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BatallaNaval] SET  READ_WRITE 
GO

